sources:
  aMysqlDb:
    active: yes
    type: MySql
    db_host: 127.0.0.1
    db_name: test
    db_port: 3306
    db_user: root
    db_pass: 1Newington
  someOtherSource:
    active: no
    type: ExampleOther